### ISSUE TITLE
Upgrade to fabric8 kubernetes-client 5.7.2 fails with latest istio-java.client 1.7.7.1

### ISSUE THREAD

**Issue by rbaeurle** [snowdrop/istio-java-api#137]
when upgrading from fabric8 kubernetes-client 5.2.1 to 5.7.2 we get the following error while creating an VirtualService object:

java.lang.NoSuchMethodError: io/fabric8/kubernetes/client/dsl/base/HasMetadataOperation.<init>(Lio/fabric8/kubernetes/client/dsl/base/OperationContext;)V (loaded from jar:file:/app.jar!/BOOT-INF/lib/kubernetes-client-5.7.2.jar!/ by org.springframework.boot.loader.LaunchedURLClassLoader@bb088dad) called from class me.snowdrop.istio.client.internal.operation.networking.v1beta1.VirtualServiceOperationImpl (loaded from jar:file:/app.jar!/BOOT-INF/lib/istio-client-1.7.7.1.jar!/ by org.springframework.boot.loader.LaunchedURLClassLoader@bb088dad).
	at me.snowdrop.istio.client.internal.operation.networking.v1beta1.VirtualServiceOperationImpl.<init>(VirtualServiceOperationImpl.java:26)
	at me.snowdrop.istio.client.internal.operation.networking.v1beta1.VirtualServiceOperationImpl.<init>(VirtualServiceOperationImpl.java:22)
	at me.snowdrop.istio.client.DefaultIstioClient.v1beta1VirtualService(DefaultIstioClient.java:130)

**Comment by Etone** [comment]
Any news on this? We can not upgrade our K8s Clusters to 1.21 due to this issue

**Comment by FWiesner** [comment]
we are struck by this as well now. I might have a look tomorrow

**Comment by metacosm** [comment]
I started having a look at it. See #141.

**Comment by foal** [comment]
Any progress on it?

**Comment by Tan-JiaLiang** [comment]
Hi @metacosm , when will the PR #141 merge?

**Comment by metacosm** [comment]
Please migrate to the [fabric8 client](https://github.com/fabric8io/kubernetes-client) version 5.11 and above and use the Istio client extension from that project. 

This project is now deprecated and further development will happen in the kubernetes-client project.

**Comment by Tan-JiaLiang** [comment]
Thanks @metacosm , it work in fabric8 client.
